# Übungsfragen {.unnumbered}

1.  Grenzen Sie Ethik und Moral voneinander ab.

1.  Grenzen Sie Wirtschaftsethik vom Begriff der Ethik ab. Diskutieren Sie dabei unterschiedliche Abgrenzungsmöglichkeiten


1.  Erläutern Sie die Begriffe Tugendethik, Pflichtenethik und Utilitarismus/teleologische Ethik.

1. Inwiefern gibt es aus teleologischer Perspektive eine Pflicht positives Wissen zu erlangen?

1.  Grenzen Sie Vertragstheorien von der Diskursethik ab. Welche Eigenschaften muss nach Auffassung der Diskursethik ein Diskurs erfüllen, damit sein Ergebnis ethische Relevanz aufweist?

1. Halten Sie diese Anforderungen für erfüllbar? Welche halten Sie für besonders problematisch?

1. Auf wen oder was kann sich die Forderung nach Gerechtigkeit alles beziehen?

1. Was bedeutet formale Gerechtigkeit?

1. Welche vier grundlegenden Arten materialer Gerechtigkeit kennen Sie? 

1. Was meint 	&bdquo;soziale Gerechtigkeit&ldquo;?

1. Welche Kritik gibt es an der Forderung nach sozialer Gerechtigkeit und was lässt sich darauf entgegnen?

1. Welche Rechtfertigungsgründe für Ungleichheit/ ungleiche Verfügungsgewalt über Ressourcen lassen sich angeben?

1. Welche fünf Grundpostulate der sozialen Verteilungsgerechtigkeit haben wir hergleitet?

1. Wer kommt als Verantwortungsträger/Verantwortungssubjekt im Kontext der internationalen Beziehungen in Frage?

1. Was unterscheidet relationale von nicht-relationaler Verantwortung?

1. Welche Zurechnungsgründe für Verantwortung lassen sich laut @hahn_globale_2017 im Kontext der internationalen Verantwortung angeben?

1. Was bedeuten &bdquo;theoretische&ldquo; und &bdquo;praktische&ldquo; Vernunft?

1. Ist KI zu Vernunft in diesem Sinne fähig?

1. Kann KI Verantwortung übernehmen?

1. Wenn das so wäre, hätten wir dann eine Verantwortung gegenüber der KI?

1. Gefährdet KI die menschliche Autorenschaft für menschliche Handlungen?
